In [1]:
from numpy import array
from scipy.linalg import lu




In [2]:
# square matrix
A = array([[1,2,3], [4,5,6], [7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# LU decomposition
# A = P.L.U

P, L, U = lu(A)

In [10]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [11]:
L

array([[1.        , 0.        , 0.        ],
       [0.14285714, 1.        , 0.        ],
       [0.57142857, 0.5       , 1.        ]])

In [12]:
U

array([[7.00000000e+00, 8.00000000e+00, 9.00000000e+00],
       [0.00000000e+00, 8.57142857e-01, 1.71428571e+00],
       [0.00000000e+00, 0.00000000e+00, 1.11022302e-16]])

In [13]:
# Reconstruction
B = P.dot(L).dot(U)

In [14]:
B

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [16]:
# QR decomposition
'''
m*m for Q
m*n for R

'''
# 3x2 matrix
AA = array([[1,2],[3,4],[5,6]])
AA

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
from numpy.linalg import qr

Q, R = qr(AA, 'complete')


In [19]:
Q

array([[-0.16903085,  0.89708523,  0.40824829],
       [-0.50709255,  0.27602622, -0.81649658],
       [-0.84515425, -0.34503278,  0.40824829]])

In [20]:
R

array([[-5.91607978, -7.43735744],
       [ 0.        ,  0.82807867],
       [ 0.        ,  0.        ]])

In [21]:
#reconstruct 
BB = Q.dot(R)

In [22]:
print(BB)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
